### ISSUE TITLE
Flesh out roadmap for additional celestial notifications

### ISSUE THREAD

**Issue by MitchellDill** [MitchellDill/moonar#15]
Once the MVP is done, I'll want to plan out future features (that don't bloat too much).

**Potential features**

- [ ] Which planets are in which constellations

- [ ] NEO stuff? Comets, et al?

- [ ] Lunar and solar eclipses

**Comment by MitchellDill** [comment]
Zodiacs were integrated around full/new moon already--further integration is still on the docket, but probably less exciting than other potentialities.

Next milestone is going to be centered on upgrading aesthetics of the components that already exist--additional celestial info will be pushed to a subsequent milestone.
